### ISSUE TITLE
As parking.bz.it user I would like to see parking forecasts correctly

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/parking-app#12] opened 2024-09-05 19:59 UTC
We have since quite a long time now a good forecasting model for parking data, e.g.:

![Image](https://github.com/user-attachments/assets/e537d1d0-e11e-4e9b-b3c6-a9a1f4cee012)

On the other side, the forecasts are displayed in these plots not correctly. In particular the first value of the time series should be the real-time measurement, on the time axis we should have then displayed the corresponding forecasts in the future.

![Image](https://github.com/user-attachments/assets/c2fbb680-e924-4b65-8d68-bdf9c060b4e8)

The request is therefore to correct this visualization in the parking.bz.it APP. Please note that also the legend has to be fixed.

**Comment by dulvui** [comment] 2024-09-06 12:12
The problem is now fixed on testing.
https://parking.opendatahub.testingmachine.eu/

The problem was that to the grapgh, the actual value was added, but since we have the 2 datatypes "free" and "occupied", both where added and so the graph looked and was wrong. Now only the "free" value is  added and also the "5min" in the legend shows now "0min"

**Comment by rcavaliere** [comment] 2024-09-11 09:15
@dulvui as just told, we have still issues for Bressanone and Brunico. Can you please check?

**Comment by dulvui** [comment] 2024-09-11 11:09
@rcavaliere Now it is fixed on testing
https://parking.opendatahub.testingmachine.eu/?location=bressanone

**Closed** 2024-09-11 11:11 UTC
Labels: bug
